version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: ${DB_SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      #- ./db_script.sql:/docker-entrypoint-initdb.d/init_db_script.sql

  productos:
    build: ./backend/ms_producto
    ports:
      - "9001:8080"
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=GestionInventario;User Id=sa;Password=${DB_SA_PASSWORD};TrustServerCertificate=True"

  transacciones:
    build: ./backend/ms_transaccion
    ports:
      - "9002:8080"
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=GestionInventario;User Id=sa;Password=${DB_SA_PASSWORD};TrustServerCertificate=True"
      Servicios__Productos: http://productos:8080
  frontend:
    build: ./frontend/gestion
    ports:
      - "9003:80"
    depends_on:
      - productos
      - transacciones

volumes:
  mssql_data:
